#!/usr/bin/env python3

#  Automatically generated by kazoo/templates/glue/language_wrappers/mini-cv-python
#  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
#  This is an input file for the DMT tool "aadl2glueC". It is imported
#  at runtime and its role is to populate DMT's AST prior to executing the
#  B mapper functions.

from dmt.commonPy import aadlAST as ast

ast.g_apLevelContainers = dict()

# Interface "ClearBuffer"
sp = ast.ApLevelContainer("ClearBuffer")
ast.g_apLevelContainers["ClearBuffer"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = ClearBuffer
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["ClearBuffer", "C", "C", "datacompressor", sp._fpgaConfigurations])
sp._language = "C"


# Interface "ReadData"
sp = ast.ApLevelContainer("ReadData")
ast.g_apLevelContainers["ReadData"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::CompressorDataBuffer")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("dataOut", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "CompressorDataBuffer"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("ReadData", "dataOut", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("ReadData", "dataOut", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("byteOffset", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("ReadData", "byteOffset", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("ReadData", "byteOffset", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("bytesToRead", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("ReadData", "bytesToRead", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("ReadData", "bytesToRead", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("bytesWritten", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("ReadData", "bytesWritten", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("ReadData", "bytesWritten", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = ReadData
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["ReadData", "C", "C", "datacompressor", sp._fpgaConfigurations])
sp._language = "C"


# Interface "StartCompression"
sp = ast.ApLevelContainer("StartCompression")
ast.g_apLevelContainers["StartCompression"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = StartCompression
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["StartCompression", "C", "C", "datacompressor", sp._fpgaConfigurations])
sp._language = "C"


# Interface "Status"
sp = ast.ApLevelContainer("Status")
ast.g_apLevelContainers["Status"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::CompressorState")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("currentStatus", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "CompressorState"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Status", "currentStatus", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Status", "currentStatus", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("compressedDataLength", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Status", "compressedDataLength", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Status", "compressedDataLength", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Status
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Status", "C", "C", "datacompressor", sp._fpgaConfigurations])
sp._language = "C"


# Interface "WriteBuffer"
sp = ast.ApLevelContainer("WriteBuffer")
ast.g_apLevelContainers["WriteBuffer"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::CompressorDataBuffer")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("dataBuffer", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "CompressorDataBuffer"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("WriteBuffer", "dataBuffer", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("WriteBuffer", "dataBuffer", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("dataLength", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("WriteBuffer", "dataLength", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("WriteBuffer", "dataLength", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = WriteBuffer
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["WriteBuffer", "C", "C", "datacompressor", sp._fpgaConfigurations])
sp._language = "C"



