/* Body file for function DataCompressor
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "datacompressor_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void datacompressor_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned datacompressor_initialized = 0;
void init_datacompressor(void)
{
   if (0 == datacompressor_initialized) {
      datacompressor_initialized = 1;
      // Call user code startup function
      extern void datacompressor_startup(void);
      datacompressor_startup();
      datacompressor_initialized = 2;
   }
}
void datacompressor_ClearBuffer(void)
{
   sender_pid = datacompressor_clearbuffer_get_sender();

   //  Directly call user code, no parameters to pass
   extern void datacompressor_PI_ClearBuffer(void);
   datacompressor_PI_ClearBuffer();
   // puts ("datacompressor_clearbuffer called");
}




void datacompressor_ReadData
      (char *OUT_dataout, size_t *OUT_dataout_len,
       const char *IN_byteoffset, size_t IN_byteoffset_len,
       const char *IN_bytestoread, size_t IN_bytestoread_len,
       char *OUT_byteswritten, size_t *OUT_byteswritten_len)

{
   sender_pid = datacompressor_readdata_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void datacompressor_PI_ReadData
      (asn1SccCompressorDataBuffer *,
       const asn1SccT_UInt32 *,
       const asn1SccT_UInt32 *,
       asn1SccT_UInt32 *);





   // Call user code
   datacompressor_PI_ReadData ((asn1SccCompressorDataBuffer *)OUT_dataout, (asn1SccT_UInt32 *)IN_byteoffset, (asn1SccT_UInt32 *)IN_bytestoread, (asn1SccT_UInt32 *)OUT_byteswritten);

}




void datacompressor_StartCompression(void)
{
   sender_pid = datacompressor_startcompression_get_sender();

   //  Directly call user code, no parameters to pass
   extern void datacompressor_PI_StartCompression(void);
   datacompressor_PI_StartCompression();
   // puts ("datacompressor_startcompression called");
}




void datacompressor_Status
      (char *OUT_currentstatus, size_t *OUT_currentstatus_len,
       char *OUT_compresseddatalength, size_t *OUT_compresseddatalength_len)

{
   sender_pid = datacompressor_status_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void datacompressor_PI_Status
      (asn1SccCompressorState *,
       asn1SccT_UInt32 *);





   // Call user code
   datacompressor_PI_Status ((asn1SccCompressorState *)OUT_currentstatus, (asn1SccT_UInt32 *)OUT_compresseddatalength);

}




void datacompressor_WriteBuffer
      (const char *IN_databuffer, size_t IN_databuffer_len,
       const char *IN_datalength, size_t IN_datalength_len)

{
   sender_pid = datacompressor_writebuffer_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void datacompressor_PI_WriteBuffer
      (const asn1SccCompressorDataBuffer *,
       const asn1SccT_UInt32 *);





   // Call user code
   datacompressor_PI_WriteBuffer ((asn1SccCompressorDataBuffer *)IN_databuffer, (asn1SccT_UInt32 *)IN_datalength);

}

