/* Header file for function DataUncompressor
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void datauncompressor_startup(void);

/* Provided interfaces */
void datauncompressor_PI_ClearBuffer( void );


void datauncompressor_PI_ReadData( asn1SccCompressorDataBuffer *, const asn1SccT_UInt32 *, const asn1SccT_UInt32 *, asn1SccT_UInt32 * );


void datauncompressor_PI_StartUncompression( void );


void datauncompressor_PI_Status( asn1SccCompressorState *, asn1SccT_UInt32 * );


void datauncompressor_PI_WriteBuffer( const asn1SccCompressorDataBuffer *, const asn1SccT_UInt32 * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
