/* Header file for function TestDataCompressor
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void testdatacompressor_startup(void);

/* Provided interfaces */
void testdatacompressor_PI_RunOnce( void );

/* Required interfaces */
extern void testdatacompressor_RI_ClearBuffer( void );


extern void testdatacompressor_RI_ReadData( asn1SccCompressorDataBuffer *, const asn1SccT_UInt32 *, const asn1SccT_UInt32 *, asn1SccT_UInt32 * );


extern void testdatacompressor_RI_StartCompression( void );


extern void testdatacompressor_RI_Status( asn1SccCompressorState *, asn1SccT_UInt32 * );


extern void testdatacompressor_RI_WriteBuffer( const asn1SccCompressorDataBuffer *, const asn1SccT_UInt32 * );


#ifdef __cplusplus
}
#endif
