/*
 * @copyright 2026 KISPE Space Systems Ltd.
 *
 * Licensed under the ESA Public License (ESA-PL) Permissive (Type 3),
 * Version 2.4 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://essr.esa.int/license/list
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Body file for function TestDataCompressor
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten
*/
#include "testdatacompressor.h"
#include <string.h>

static const char* TEST_PATTERN =
    "The quick brown fox jumps over the lazy dog. ";

#define TEST_INPUT_LENGTH 1024u
#define CHUNK_SIZE 32u

void testdatacompressor_startup(void)
{
    puts("[TestDataCompressor] Startup");
}

void testdatacompressor_PI_RunOnce(void)
{
    static bool runOnce = false;
    if (runOnce)
        return;
    runOnce = true;

    asn1SccCompressorState compressorState = CompressorState_compressor_not_initialized;
    asn1SccT_UInt32 compressedLength = 0;

    // ============================================================
    // Wait for compressor to become ready
    // ============================================================

    puts("[TDC] Waiting for compressor initialization");
    do
    {
        testdatacompressor_RI_Status(&compressorState, &compressedLength);
    } while (compressorState != CompressorState_compressor_idle);
    puts("[TDC] Compressor ready");

    // ============================================================
    // Build a highly-compressible 1024-byte input
    // ============================================================

    uint8_t inputData[TEST_INPUT_LENGTH];
    size_t patternLength = strlen(TEST_PATTERN);
    for (uint32_t byteIndex = 0; byteIndex < TEST_INPUT_LENGTH; ++byteIndex)
        inputData[byteIndex] = (uint8_t)TEST_PATTERN[byteIndex % patternLength];

    printf("[TDC] Input: %u bytes of repeating text (\"%s\")\n",
           (unsigned)TEST_INPUT_LENGTH, TEST_PATTERN);

    // ============================================================
    // Write input to compressor in 32-byte chunks
    // ============================================================

    puts("[--- 1] Writing input buffer");

    for (uint32_t byteOffset = 0; byteOffset < TEST_INPUT_LENGTH; byteOffset += CHUNK_SIZE)
    {
        asn1SccCompressorDataBuffer chunk;
        asn1SccT_UInt32 bytesThisChunk =
            (TEST_INPUT_LENGTH - byteOffset) < CHUNK_SIZE
                ? (TEST_INPUT_LENGTH - byteOffset)
                : CHUNK_SIZE;

        memcpy(chunk.arr, inputData + byteOffset, bytesThisChunk);
        testdatacompressor_RI_WriteBuffer(&chunk, &bytesThisChunk);
    }

    // ============================================================
    // Start compression (blocking) and check result
    // ============================================================

    puts("[--- 2] Starting compression");
    testdatacompressor_RI_StartCompression();

    testdatacompressor_RI_Status(&compressorState, &compressedLength);

    if (compressorState == CompressorState_compressor_success)
        printf("[TDC] Compression success: %u -> %u bytes (%.1f%% of original)\n",
               (unsigned)TEST_INPUT_LENGTH,
               (unsigned)compressedLength,
               (100.0 * (double)compressedLength) / (double)TEST_INPUT_LENGTH);
    else
    {
        printf("[TDC] Compression failed (state: %u)\n", (unsigned)compressorState);
        return;
    }

    // ============================================================
    // Read the compressed output back out and print as hex
    // ============================================================

    puts("[TDC] Compressed output (hex):");

    uint32_t totalRead = 0;
    while (totalRead < compressedLength)
    {
        asn1SccCompressorDataBuffer outChunk;
        asn1SccT_UInt32 bytesRemaining = compressedLength - totalRead;
        asn1SccT_UInt32 bytesToRead =
            bytesRemaining < CHUNK_SIZE ? bytesRemaining : CHUNK_SIZE;
        asn1SccT_UInt32 byteOffset = totalRead;
        asn1SccT_UInt32 bytesWritten = 0;

        testdatacompressor_RI_ReadData(&outChunk, &byteOffset, &bytesToRead, &bytesWritten);

        if (bytesWritten == 0)
        {
            printf("[TDC] ReadData returned 0 bytes at offset %u\n", (unsigned)totalRead);
            return;
        }

        for (asn1SccT_UInt32 i = 0; i < bytesWritten; ++i)
            printf("%02x", (unsigned char)outChunk.arr[i]);
        printf("\n");

        totalRead += bytesWritten;
    }

    testdatacompressor_RI_ClearBuffer();
    puts("[TDC] Done");
}
