/* ASN.1 System configuration file for function UartOtherEnd
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/system_config/function.tmplt)
 */
#define __NEED_T_UInt8_ACN
#define __NEED_T_UInt8_ACN
