/* Body file for function UartOtherEnd
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "uartotherend_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void uartotherend_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInituartotherend(void);

unsigned uartotherend_initialized = 0;
void init_uartotherend(void)
{
   if (0 == uartotherend_initialized) {
      uartotherend_initialized = 1;
      // Initialize C to call elaboration functions
      CInituartotherend();
      uartotherend_initialized = 2;
   }
}
void uartotherend_samrh71tx
      (const char *IN_ibyteout, size_t IN_ibyteout_len)

{
   sender_pid = uartotherend_samrh71tx_get_sender();
   
   static asn1SccT_UInt8 IN_IBYTEOUT;
   int ibyteout_error_code = 0;

   if (0 != Decode_ACN_T_UInt8 (&IN_IBYTEOUT, (void *)IN_ibyteout, IN_ibyteout_len, &ibyteout_error_code)) {
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void uartotherend_PI_samrh71tx
      (const asn1SccT_UInt8 *);





   // Call user code
   uartotherend_PI_samrh71tx (&IN_IBYTEOUT);

}

