/* Header file for function DataUncompressor
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm_if-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#include "C_ASN1_Types.h"
#ifdef __cplusplus
extern "C" {
#endif

#include "datauncompressor.h"

// Function initialization - calls user startup code of all dependent functions
void init_datauncompressor(void);


/* Provided interfaces */
void datauncompressor_ClearBuffer(void);


void datauncompressor_ReadData
      (char *OUT_dataout, size_t *OUT_dataout_len,
       const char *IN_byteoffset, size_t IN_byteoffset_len,
       const char *IN_bytestoread, size_t IN_bytestoread_len,
       char *OUT_byteswritten, size_t *OUT_byteswritten_len);



void datauncompressor_StartUncompression(void);


void datauncompressor_Status
      (char *OUT_currentstatus, size_t *OUT_currentstatus_len,
       char *OUT_decompresseddatalength, size_t *OUT_decompresseddatalength_len);



void datauncompressor_WriteBuffer
      (const char *IN_databuffer, size_t IN_databuffer_len,
       const char *IN_datalength, size_t IN_datalength_len);


#ifdef __cplusplus
}
#endif

