/* Header file for function DataCompressor
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void datacompressor_startup(void);

/* Provided interfaces */
void datacompressor_PI_ClearBuffer( void );


void datacompressor_PI_ReadData( asn1SccCompressorDataBuffer *, const asn1SccT_UInt32 *, const asn1SccT_UInt32 *, asn1SccT_UInt32 * );


void datacompressor_PI_StartCompression( void );


void datacompressor_PI_Status( asn1SccCompressorState *, asn1SccT_UInt32 * );


void datacompressor_PI_WriteBuffer( const asn1SccCompressorDataBuffer *, const asn1SccT_UInt32 * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
