/* ASN.1 System configuration file for function TestCompressUncompress
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/system_config/function.tmplt)
 */
#define __NEED_T_UInt8_ACN
#define __NEED_CompressorDataBuffer_NATIVE
#define __NEED_T_UInt32_NATIVE
#define __NEED_T_UInt32_NATIVE
#define __NEED_T_UInt32_NATIVE




#define __NEED_CompressorState_NATIVE
#define __NEED_T_UInt32_NATIVE


#define __NEED_CompressorDataBuffer_NATIVE
#define __NEED_T_UInt32_NATIVE




#define __NEED_CompressorDataBuffer_NATIVE
#define __NEED_T_UInt32_NATIVE
#define __NEED_T_UInt32_NATIVE
#define __NEED_T_UInt32_NATIVE




#define __NEED_CompressorState_NATIVE
#define __NEED_T_UInt32_NATIVE


#define __NEED_CompressorDataBuffer_NATIVE
#define __NEED_T_UInt32_NATIVE


#define __NEED_T_UInt8_ACN
