#!/usr/bin/env python3

#  Automatically generated by kazoo/templates/glue/language_wrappers/mini-cv-python
#  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
#  This is an input file for the DMT tool "aadl2glueC". It is imported
#  at runtime and its role is to populate DMT's AST prior to executing the
#  B mapper functions.

from dmt.commonPy import aadlAST as ast

ast.g_apLevelContainers = dict()

# Interface "RunOnce"
sp = ast.ApLevelContainer("RunOnce")
ast.g_apLevelContainers["RunOnce"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::Interface_Cyclic_Offset = 0
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 1024
# Taste::InterfaceName = RunOnce
# Taste::RCMoperationKind = cyclic
# Taste::RCMperiod = 5000 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["RunOnce", "C", "C", "testcompressuncompress", sp._fpgaConfigurations])
sp._language = "C"


# Interface "samrh71rx"
sp = ast.ApLevelContainer("samrh71rx")
ast.g_apLevelContainers["samrh71rx"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::T_UInt8")
param._encoding = "ACN"
subProgramFeature = ast.AadlSubProgramFeature("iByteIn", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt8"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("samrh71rx", "iByteIn", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("samrh71rx", "iByteIn", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Associated_Queue_Size = 1
# Taste::Communication_Layer = default
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 1024
# Taste::InterfaceName = samrh71rx
# Taste::RCMoperationKind = sporadic
# Taste::RCMperiod = 0 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["samrh71rx", "C", "C", "testcompressuncompress", sp._fpgaConfigurations])
sp._language = "C"

# Interface "Comp_ClearBuffer"
sp = ast.ApLevelContainer("Comp_ClearBuffer")
ast.g_apLevelContainers["Comp_ClearBuffer"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Comp_ClearBuffer
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Comp_ClearBuffer", "C", "C", "testcompressuncompress", sp._fpgaConfigurations])
sp._language = "C"


# Interface "Comp_ReadData"
sp = ast.ApLevelContainer("Comp_ReadData")
ast.g_apLevelContainers["Comp_ReadData"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::CompressorDataBuffer")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("dataOut", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "CompressorDataBuffer"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Comp_ReadData", "dataOut", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Comp_ReadData", "dataOut", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("byteOffset", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Comp_ReadData", "byteOffset", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Comp_ReadData", "byteOffset", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("bytesToRead", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Comp_ReadData", "bytesToRead", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Comp_ReadData", "bytesToRead", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("bytesWritten", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Comp_ReadData", "bytesWritten", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Comp_ReadData", "bytesWritten", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Comp_ReadData
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Comp_ReadData", "C", "C", "testcompressuncompress", sp._fpgaConfigurations])
sp._language = "C"


# Interface "Comp_StartCompression"
sp = ast.ApLevelContainer("Comp_StartCompression")
ast.g_apLevelContainers["Comp_StartCompression"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Comp_StartCompression
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Comp_StartCompression", "C", "C", "testcompressuncompress", sp._fpgaConfigurations])
sp._language = "C"


# Interface "Comp_Status"
sp = ast.ApLevelContainer("Comp_Status")
ast.g_apLevelContainers["Comp_Status"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::CompressorState")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("currentStatus", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "CompressorState"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Comp_Status", "currentStatus", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Comp_Status", "currentStatus", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("compressedDataLength", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Comp_Status", "compressedDataLength", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Comp_Status", "compressedDataLength", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Comp_Status
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Comp_Status", "C", "C", "testcompressuncompress", sp._fpgaConfigurations])
sp._language = "C"


# Interface "Comp_WriteBuffer"
sp = ast.ApLevelContainer("Comp_WriteBuffer")
ast.g_apLevelContainers["Comp_WriteBuffer"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::CompressorDataBuffer")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("dataBuffer", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "CompressorDataBuffer"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Comp_WriteBuffer", "dataBuffer", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Comp_WriteBuffer", "dataBuffer", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("dataLength", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Comp_WriteBuffer", "dataLength", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Comp_WriteBuffer", "dataLength", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Comp_WriteBuffer
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Comp_WriteBuffer", "C", "C", "testcompressuncompress", sp._fpgaConfigurations])
sp._language = "C"


# Interface "Uncomp_ClearBuffer"
sp = ast.ApLevelContainer("Uncomp_ClearBuffer")
ast.g_apLevelContainers["Uncomp_ClearBuffer"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Uncomp_ClearBuffer
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Uncomp_ClearBuffer", "C", "C", "testcompressuncompress", sp._fpgaConfigurations])
sp._language = "C"


# Interface "Uncomp_ReadData"
sp = ast.ApLevelContainer("Uncomp_ReadData")
ast.g_apLevelContainers["Uncomp_ReadData"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::CompressorDataBuffer")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("dataOut", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "CompressorDataBuffer"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Uncomp_ReadData", "dataOut", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Uncomp_ReadData", "dataOut", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("byteOffset", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Uncomp_ReadData", "byteOffset", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Uncomp_ReadData", "byteOffset", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("bytesToRead", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Uncomp_ReadData", "bytesToRead", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Uncomp_ReadData", "bytesToRead", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("bytesWritten", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Uncomp_ReadData", "bytesWritten", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Uncomp_ReadData", "bytesWritten", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Uncomp_ReadData
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Uncomp_ReadData", "C", "C", "testcompressuncompress", sp._fpgaConfigurations])
sp._language = "C"


# Interface "Uncomp_StartUncompression"
sp = ast.ApLevelContainer("Uncomp_StartUncompression")
ast.g_apLevelContainers["Uncomp_StartUncompression"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Uncomp_StartUncompression
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Uncomp_StartUncompression", "C", "C", "testcompressuncompress", sp._fpgaConfigurations])
sp._language = "C"


# Interface "Uncomp_Status"
sp = ast.ApLevelContainer("Uncomp_Status")
ast.g_apLevelContainers["Uncomp_Status"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::CompressorState")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("currentStatus", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "CompressorState"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Uncomp_Status", "currentStatus", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Uncomp_Status", "currentStatus", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("decompressedDataLength", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Uncomp_Status", "decompressedDataLength", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Uncomp_Status", "decompressedDataLength", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Uncomp_Status
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Uncomp_Status", "C", "C", "testcompressuncompress", sp._fpgaConfigurations])
sp._language = "C"


# Interface "Uncomp_WriteBuffer"
sp = ast.ApLevelContainer("Uncomp_WriteBuffer")
ast.g_apLevelContainers["Uncomp_WriteBuffer"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::CompressorDataBuffer")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("dataBuffer", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "CompressorDataBuffer"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Uncomp_WriteBuffer", "dataBuffer", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Uncomp_WriteBuffer", "dataBuffer", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("dataLength", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("Uncomp_WriteBuffer", "dataLength", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("Uncomp_WriteBuffer", "dataLength", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = Uncomp_WriteBuffer
# Taste::labelInheritance = true
# Taste::RCMoperationKind = protected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["Uncomp_WriteBuffer", "C", "C", "testcompressuncompress", sp._fpgaConfigurations])
sp._language = "C"


# Interface "samrh71tx"
sp = ast.ApLevelContainer("samrh71tx")
ast.g_apLevelContainers["samrh71tx"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_UInt8")
param._encoding = "ACN"
subProgramFeature = ast.AadlSubProgramFeature("iByteOut", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt8"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("samrh71tx", "iByteOut", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("samrh71tx", "iByteOut", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Associated_Queue_Size = 1
# Taste::Communication_Layer = default
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 1024
# Taste::InterfaceName = samrh71tx
# Taste::labelInheritance = true
# Taste::RCMoperationKind = sporadic
# Taste::RCMperiod = 0 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = Ada
ast.g_subProgramImplementations.append(["samrh71tx", "C", "C", "testcompressuncompress", sp._fpgaConfigurations])
sp._language = "C"

