/* Body file for function TestCompressUncompress
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "testcompressuncompress_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void testcompressuncompress_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

extern void init_datacompressor(void);
extern unsigned datacompressor_initialized;
extern void init_datauncompressor(void);
extern unsigned datauncompressor_initialized;
unsigned testcompressuncompress_initialized = 0;
void init_testcompressuncompress(void)
{
   if (0 == testcompressuncompress_initialized) {
      testcompressuncompress_initialized = 1;
      // Call user code startup function
      extern void testcompressuncompress_startup(void);
      testcompressuncompress_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == datacompressor_initialized) {
          init_datacompressor();
      }
      if (0 == datauncompressor_initialized) {
          init_datauncompressor();
      }
      testcompressuncompress_initialized = 2;
   }
}
void testcompressuncompress_RunOnce(void)
{

   //  Directly call user code, no parameters to pass
   extern void testcompressuncompress_PI_RunOnce(void);
   testcompressuncompress_PI_RunOnce();
   // puts ("testcompressuncompress_runonce called");
}




void testcompressuncompress_samrh71rx
      (const char *IN_ibytein, size_t IN_ibytein_len)

{
   sender_pid = testcompressuncompress_samrh71rx_get_sender();
   
   static asn1SccT_UInt8 IN_IBYTEIN;
   int ibytein_error_code = 0;

   if (0 != Decode_ACN_T_UInt8 (&IN_IBYTEIN, (void *)IN_ibytein, IN_ibytein_len, &ibytein_error_code)) {
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void testcompressuncompress_PI_samrh71rx
      (const asn1SccT_UInt8 *);





   // Call user code
   testcompressuncompress_PI_samrh71rx (&IN_IBYTEIN);

}

