#ifndef GENERATED_ASN1SCC_uartotherend_datamodel_H
#define GENERATED_ASN1SCC_uartotherend_datamodel_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "dataview-uniq.h"

#ifdef  __cplusplus
extern "C" {
#endif


typedef enum {
    asn1Sccwait = 0
} asn1SccUartotherend_States;

// please use the following macros to avoid breaking code.
#define asn1SccUartotherend_States_wait asn1Sccwait

flag asn1SccUartotherend_States_Equal(const asn1SccUartotherend_States* pVal1, const asn1SccUartotherend_States* pVal2);

#define ERR_UARTOTHEREND_STATES		1  /*wait*/
flag asn1SccUartotherend_States_IsConstraintValid(const asn1SccUartotherend_States* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccUartotherend_States asn1SccUartotherend_States_constant;
#else
#define asn1SccUartotherend_States_constant asn1Sccwait
#endif

void asn1SccUartotherend_States_Initialize(asn1SccUartotherend_States* pVal);
/*-- asn1SccUartotherend_Context --------------------------------------------*/
typedef struct {
    asn1SccUartotherend_States state;
    flag init_done;
    asn1SccPID sender;
    asn1SccPID offspring;

} asn1SccUartotherend_Context;

flag asn1SccUartotherend_Context_Equal(const asn1SccUartotherend_Context* pVal1, const asn1SccUartotherend_Context* pVal2);

#define ERR_UARTOTHEREND_CONTEXT		136  /**/
#define ERR_UARTOTHEREND_CONTEXT_STATE_2		106  /**/
#define ERR_UARTOTHEREND_CONTEXT_INIT_DONE		111  /**/
#define ERR_UARTOTHEREND_CONTEXT_SENDER_2		121  /**/
#define ERR_UARTOTHEREND_CONTEXT_OFFSPRING_2		131  /**/
flag asn1SccUartotherend_Context_IsConstraintValid(const asn1SccUartotherend_Context* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccUartotherend_Context asn1SccUartotherend_Context_constant;
#else
#define asn1SccUartotherend_Context_constant {.state = asn1Sccwait, .init_done = FALSE, .sender = asn1Sccdatacompressor, .offspring = asn1Sccdatacompressor}
#endif

void asn1SccUartotherend_Context_Initialize(asn1SccUartotherend_Context* pVal);
typedef enum {
    asn1Sccnoerror_present = 1,
    asn1Sccencodeerror_present = 2,
    asn1Sccdecodeerror_present = 3
} asn1SccUartotherend_T_Runtime_Error_Selection;

// please use the following macros to avoid breaking code.
#define asn1SccUartotherend_T_Runtime_Error_Selection_noerror_present asn1Sccnoerror_present
#define asn1SccUartotherend_T_Runtime_Error_Selection_encodeerror_present asn1Sccencodeerror_present
#define asn1SccUartotherend_T_Runtime_Error_Selection_decodeerror_present asn1Sccdecodeerror_present

flag asn1SccUartotherend_T_Runtime_Error_Selection_Equal(const asn1SccUartotherend_T_Runtime_Error_Selection* pVal1, const asn1SccUartotherend_T_Runtime_Error_Selection* pVal2);

#define ERR_UARTOTHEREND_T_RUNTIME_ERROR_SELECTION		6  /*noerror-present | encodeerror-present | decodeerror-present*/
flag asn1SccUartotherend_T_Runtime_Error_Selection_IsConstraintValid(const asn1SccUartotherend_T_Runtime_Error_Selection* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccUartotherend_T_Runtime_Error_Selection asn1SccUartotherend_T_Runtime_Error_Selection_constant;
#else
#define asn1SccUartotherend_T_Runtime_Error_Selection_constant asn1Sccnoerror_present
#endif

void asn1SccUartotherend_T_Runtime_Error_Selection_Initialize(asn1SccUartotherend_T_Runtime_Error_Selection* pVal);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
