/* Header file for function TestCompressUncompress
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void testcompressuncompress_startup(void);

/* Provided interfaces */
void testcompressuncompress_PI_RunOnce( void );


void testcompressuncompress_PI_samrh71rx( const asn1SccT_UInt8 * );

/* Required interfaces */
extern void testcompressuncompress_RI_Comp_ClearBuffer( void );


extern void testcompressuncompress_RI_Comp_ReadData( asn1SccCompressorDataBuffer *, const asn1SccT_UInt32 *, const asn1SccT_UInt32 *, asn1SccT_UInt32 * );


extern void testcompressuncompress_RI_Comp_StartCompression( void );


extern void testcompressuncompress_RI_Comp_Status( asn1SccCompressorState *, asn1SccT_UInt32 * );


extern void testcompressuncompress_RI_Comp_WriteBuffer( const asn1SccCompressorDataBuffer *, const asn1SccT_UInt32 * );


extern void testcompressuncompress_RI_Uncomp_ClearBuffer( void );


extern void testcompressuncompress_RI_Uncomp_ReadData( asn1SccCompressorDataBuffer *, const asn1SccT_UInt32 *, const asn1SccT_UInt32 *, asn1SccT_UInt32 * );


extern void testcompressuncompress_RI_Uncomp_StartUncompression( void );


extern void testcompressuncompress_RI_Uncomp_Status( asn1SccCompressorState *, asn1SccT_UInt32 * );


extern void testcompressuncompress_RI_Uncomp_WriteBuffer( const asn1SccCompressorDataBuffer *, const asn1SccT_UInt32 * );


extern void testcompressuncompress_RI_samrh71tx( const asn1SccT_UInt8 * );


#ifdef __cplusplus
}
#endif
